sudo: required

language: ruby


env:
  global:
    secure: V5j/hiVw4mEh6wIdGU8dd9C6w3nVe8aWyjeMoWf6zbnFXknzHVIXrHXk5aiYYtk4aSji3EMtOKEHYOfv+qDBPOHnVucmwwNYv47dFxw7LgI+dfmTXkKoiJ76V7keba5kKhSVUymcX2ziImf4gYZeNnBPUsbwsrQCiq5aNSfLKQfCuUyT4cNfi39bZNHy3dGqbHX4MgPmMGl+Nns9VBg3+m1idhUdkGylJTdbR/PFE9Fpjt8sXWwoD0q8f81PkIsLWYeY0HSnKJxOFNQfL0suwoymbWigINlMBu97FDotJ6DXOq4CB/IM2IOK5Z2viQkaj7KAXfYYqED3vfMij7z4kdhRN/avJ/KtBE+yNZLjKMC9HqjbQrA5qJnIQRuD3wuZQh+0cp+8td39xY5SRqPQoW0I1NKmqNsiOIRtNec7HjV0t8LzlE5E7r6URdPRu/sqFHox+g5uuDhylzWafasVqpTO9MHjG3AUphJ5mDMuEPQWoPnFcewzxm6pfTEKjyKD+51pF0ysjgCGaK23yVjJSCzjfdRrsRGchvjivAYSQH8sNeUgVxrrEHg97MMy/GDpZUK3Cr5OriOgp1zhrrUbEt1wqvdrMmPy1OshKPZUXvohD3PRx3JZsTNfMrB3b63B9JcAU5mCj/2t7yfIiY0xDg+q9LEiMmqT8Tl/C11E3ok=


services:
  - docker

before_install:
  - docker pull jekyll/jekyll:latest

script: docker run -v $(pwd):/srv/jekyll -e JEKYLL_UID=$(id -u) -e JEKYLL_GID=$(id -g) jekyll/jekyll:latest jekyll build

branches:
  only:
  - master

deploy:
  provider: pages
  local-dir: _site
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true  # Keep deployed site history
  on:
    branch: master