sudo: required

language: ruby

services:
  - docker

before_install:
  - docker pull jekyll/jekyll:3.7.3

script: cd docs && docker run -w /srv/jekyll/docs -v $(pwd):/srv/jekyll -e JEKYLL_DATA_DIR=/srv/jekyll/docs jekyll/jekyll:3.7.3 jekyll build

branches:
  only:
  - master

sudo: false # route your build to the container-based infrastructure for a faster build

# cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
#notifications:
#  email: false

deploy:
  provider: pages
  local-dir: docs
  target-branch: gh-pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false  # Force push
  on:
    branch: master